name: Publish package to PyPi

on:
  push:
    tags:
      - v*

jobs:
  build-release:
        runs-on: ubuntu-latest
    name: Publish to PyPI
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
      - name: Installing the package
        run: |
          pip3 install .
          pip3 install build
      - name: Build package
        run: |
          python build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
